# Generated by Django 5.0.4 on 2024-04-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump', '0002_remove_pump_status_pump_vstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
