# Generated by Django 5.0.4 on 2024-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump', '0003_mechanic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
