# Generated by Django 5.0.4 on 2024-04-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump', '0002_remove_pump_status_pump_vstatus'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('delivery_boy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pump.deliveryboy')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pump.fuel')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pump.mechanic')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pump.pump')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.newuser')),
            ],
        ),
    ]
