# Generated by Django 5.0.4 on 2024-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mechanic_needed',
            field=models.BooleanField(default=False),
        ),
    ]
