# Generated by Django 5.0.4 on 2024-05-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_booking_mechanic_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
