# Generated by Django 5.0.4 on 2024-05-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_booking_payment_status_newuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_boy_contacted',
            field=models.BooleanField(default=True),
        ),
    ]
