# Generated by Django 5.0.4 on 2024-05-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Adminreply',
            new_name='Admin_reply',
        ),
    ]
