# Generated by Django 5.0.4 on 2024-05-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_adminreply_complaint_admin_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Admin_reply',
            new_name='admin_reply',
        ),
    ]
